[LangOptions]
LanguageName=Nederlands
LanguageID=$0413
LanguageCodePage=0
DialogFontName=Tahoma
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
